filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/proton-server/proton-server.err.log
    multiline:
      type: pattern
      pattern: '^(\d{4}\.\d{2}\.\d{2} \d{2}:\d{2}:\d{2}\.\d+)'
      negate: true
      match: after

output.kafka:
  hosts: ["kafka:9092"]
  topic: logs  